version: 2.1

commands:
  run_serial:
  description: "Build and run tests"
  parameters:
    workspace_member:
      type: string
    cache_key:
      type: string
    flags:
      type: string
      default: ""
  steps:
    - checkout
    - setup_environment:
        cache_key: << parameters.cache_key >>
    - run:
        no_output_timeout: 30m
        command: cd << parameters.workspace_member >> && RUST_MIN_STACK=67108864 cargo test << parameters.flags >>
    - clear_environment:
        cache_key: << parameters.cache_key >>

  run_parallel:
    description: "Build and run tests (in parallel)"
    parameters:
      workspace_member:
        type: string
      cache_key:
        type: string
      flags:
        type: string
        default: ""
    steps:
      - checkout
      - setup_environment:
          cache_key: << parameters.cache_key >>
      - run:
          no_output_timeout: 30m
          command: |
            cd << parameters.workspace_member >>
            cargo test -- --list --format terse | sed 's/: test//' > test_names.txt
            TEST_NAMES=$(circleci tests split test_names.txt)
            for i in $(echo $TEST_NAMES | sed "s/ / /g")
            do
                RUST_MIN_STACK=67108864 cargo test $i << parameters.flags >>
            done
      - clear_environment:
          cache_key: << parameters.cache_key >>

jobs:
  rust_stable:
    docker:
      - image: cimg/rust:1.62
    resource_class: small
    steps:
      - run_serial:
          workspace_member: .
          cache_key: aleo-stable-cache

workflows:
  version: 2

  main-workflow:
    jobs:
      - rust_stable
